name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set image tags
      run: |
        echo "time_tag=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV
        echo "repo=ghcr.io/${{ github.repository }}" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./base           # 👈 this is the build context directory
        file: ./base/Dockerfile   # 👈 explicitly set the Dockerfile
        push: true
        tags: |
          ${{ env.repo }}:base
